#include <stdio.h>
#include <ncurses.h>
#include <stdlib.h>
#include <string.h>
#include "Name.h"
#include "menu.h"
#include "schueler_level.h"
#include "student_level.h"
#include "experte_level.h"
#include "netzwerk_sicherheit_level.h"
#include "netzwerk_level.h"
#include "kryptographie.h"