#!/bin/bash

# script to create a lxd network bridge
# $1 = level

function cd_return {                                                    # cd to former working dir
    echo -n "[$(basename "$0")] DONE: return to path: "; cd -
}
trap cd_return EXIT                                                     # trap 'exit', run cd_return first

cd $(dirname "$0") ; . log_with_timestamp                               # cd to path/to/$0, call log_with_timestamp
echo "[$(basename "$0")] CALL: $@"

if [ $# = 0 ]; then                                                     # no parameters allowed
    echo "[$(basename "$0")] STEP: create bridge hacklab-$USER"
    sudo brctl addbr hacklab-$USER up                                   # add and start a bridge
    sudo ip link set dev hacklab-$USER up                               # add and start the L2 link
    echo "[$(basename "$0")] DONE: created bridge hacklab-$USER"
    exit 0
else
    echo "[$(basename "$0")] FAIL: invalid number of parameters"
    exit 1
fi
