#!/bin/bash

# script to delete a lxd network bridge
# $1 = level

function cd_return {
    echo -n "[$(basename "$0")] DONE: return to path: "; cd -       # cd to former working dir
}
trap cd_return EXIT                                                 # trap 'exit', run cd_return first

cd $(dirname "$0") ; . log_with_timestamp                           # cd to path/to/$0, call log_with_timestamp
echo "[$(basename "$0")] CALL: $@"

if [ $# = 0 ]; then                                                 # no parameters allowed
    echo "[$(basename "$0")] STEP: delete bridge hacklab-$USER"
    sudo ip link set dev hacklab-$USER down                         # stop and delete the L2 link
    sudo brctl delbr hacklab-$USER                                  # stop and delete bridge named $1
    echo "[$(basename "$0")] DONE: deleted bridge for level $1"
    exit 0
else
    echo "[$(basename "$0")] FAIL: invalid number of parameters"
    exit 1
fi
