#!/bin/bash

# set up given number of containers of a level (stopped, not running)

# $1 = pupil/expert or module, if student
# $2 = level
# $3 = number of containers
# $4 = optional: ISO alias/fingerprint [default = iso-alpine-utils]

function cd_return {
    echo -n "[$(basename "$0")] DONE: return to path: "; cd -                                       # cd to former working dir
}
trap cd_return EXIT                                                                                 # trap 'exit', run cd_return first

cd $(dirname "$0") ; . ./log_with_timestamp                                                         # cd to path/to/$0, 'source' log_with_timestamp
echo "[$(basename "$0")] CALL: $@"

if [ "$#" -eq 4 ] || [ "$#" -eq 3 ] ; then                                                          # only two or three parameters allowed
    if [ "$#" -eq 3 ]; then image="iso-alpine-utils"; else image="$4"; fi                           # if two parameters, use default ISO
    if [ "$2" -lt 10 ]; then level_=0"$2"; else level_="$2"; fi                                     # adjust for two-digit number sheme
    for (( container=1; container <= "$3"; container++ )); do
        if [ "$container" -lt 10 ]; then container_=0"$container"; else container_="$container"; fi
        echo "[$(basename "$0")] STEP: init container $container_"
        lxc init -p hacklab "$image" "$1"-lvl"$level_"-c"$container_"-$USER                         # profile = 'hacklab', image = $image
    done
    echo "[$(basename "$0")] DONE: created containers for level $level of module $1"
    exit 0
else
    echo "[$(basename "$0")] FAIL: invalid number of parameters"
    exit 1
fi
