#!/bin/bash

# delete containers for a level (if stopped)

# $1 = pupil/expert or module, if student
# $2 = level
# $3 = number of containers

function cd_return {
    echo -n "[$(basename "$0")] DONE: return to path: "; cd -                                       # cd to former working dir
}
trap cd_return EXIT                                                                                 # trap 'exit', run cd_return first

cd $(dirname "$0") ; . ./log_with_timestamp                                                         # cd to path/to/$0, call log_with_timestamp
echo "[$(basename "$0")] CALL: $@"

if [ $# = 3 ]                                                                                       # only two parameters allowed
then
    if [ "$2" -lt 10 ]; then level=0"$2"; else level="$2"; fi                                       # adjust for two-digit number sheme
    for((container = 1; container <= $3; container++)); do
        if [ "$container" -lt 10 ]; then container_=0"$container"; else container_="$container"; fi
        echo "[$(basename "$0")] STEP: delete container $container_"
        lxc delete $1-lvl"$level"-c"$container_"-$USER                                              # deletes a container (only if STOPPED)
    done
    echo "[$(basename "$0")] STEP: try target container"
    lxc delete $1-lvl"$level"-target-$USER                                                          # in case there is a target VM - FIXME: catch this
    echo "[$(basename "$0")] DONE: deleted containers for level $level of module $1"
    exit 0
else
    echo "[$(basename "$0")] FAIL: invalid number of parameters"
    exit 1
fi
