---
# tasks file for create_container

- name: Create the first level 1 containert
  lxd_container:
    name: lvl1-d1
    state: stopped
    source:
      type: image
      mode: pull
      #server: https://images.linuxcontainers.org
      #protocol: simplestreams
      #fingerprint: 017d8572a250      #fingerprint for 'big' Ubuntu Image
      fingerprint: 5dd7ed85ba21     #fingerprint for alpine Image 
      #alias: ubuntu/xenial/amd64
      #alias: alpine/3.7
      #alias: alpine-iso
    profiles: ["default"]
    wait_for_ipv4_addresses: false
    timeout: 600

- name: Create the second level 1 containert
  lxd_container:
    name: lvl1-d2
    state: stopped
    source:
      type: image
      mode: pull
      fingerprint: 5dd7ed85ba21
      #alias: ubuntu/xenial/amd64
      #alias: alpine-iso
    profiles: ["default"]
    wait_for_ipv4_addresses: false
    timeout: 600

- name: Create the third level 1 containert
  lxd_container:
    name: lvl1-d3
    state: stopped
    source:
      type: image
      mode: pull
      fingerprint: 5dd7ed85ba21
      #alias: ubuntu/xenial/amd64
      #alias: alpine-iso
    profiles: ["default"]
    wait_for_ipv4_addresses: false
    timeout: 600