---
# tasks file for create_container

- name: Create the first level 1 containert
  lxd_container:
    name: lvl1-d1                                       #describes the name of the first container
    state: stopped                                      #when we add a container it should not be in a running state
    source:
      type: image
      mode: pull
      fingerprint: 5dd7ed85ba21                         #fingerprint of the image we use
    profiles: ["default"]                               #describes the network and storage profile 
    wait_for_ipv4_addresses: false
    timeout: 600

- name: Create the second level 1 containert
  lxd_container:
    name: lvl1-d2
    state: stopped
    source:
      type: image
      mode: pull
      fingerprint: 5dd7ed85ba21
    profiles: ["default"]
    wait_for_ipv4_addresses: false
    timeout: 600

- name: Create the third level 1 containert
  lxd_container:
    name: lvl1-d3
    state: stopped
    source:
      type: image
      mode: pull
      fingerprint: 5dd7ed85ba21
    profiles: ["default"]
    wait_for_ipv4_addresses: false
    timeout: 600