#!/bin/bash

TEST=$(gpg --list-key | grep ADE7442014A0B09FFE775A82F9EEC022136831FB)          #key-id for hacklab public key (database)      

if [[ ! $TEST ]]; then                                                          #tests if the gpg key already exists 
    gpg --import ./ressources/hacklab-pub.gpg.asc 2> /dev/null                      #if the key does not exist, it will be added
fi