#!/bin/bash

# 1. decrypts all files someone pushed to uploadedFiles/
# 2. generates the file with all decrypted uploads
# 3. checks if there is already the header otherwise we print a header in the file allUploads
# 4. concatenates the old entries with the new ones
# 5. deletes the latest decrypted files after they have been attached to allUploads

(gpg --decrypt-files ./uploads/*.gpg) &> /dev/null                                                            
touch ./database/allUploads
(grep '^HS-Worms\ Username;submission\ data;module;level;points$' './database/allUploads' >> /dev/null) || (echo "HS-Worms Username;submission data;module;level;points" >> ./database/allUploads)
cat ./uploads/datasetHacklab-*.txt >> ./database/allUploads
yes | rm ./uploads/datasetHacklab-*