#!/bin/bash

#1. decrypts all files someone pushed to uploadedFiles/
#2. generates the file with all decrypted uploads
#3. checks if there is already the header otherwise we print a header in the file allUploads
#4. concatenates the old entries with the new ones
#5. deletes the latest decrypted files after they have been attached to allUploads

(gpg --decrypt-files ./uploadedFiles/*.gpg) &> /dev/null                                                            
touch ./summaryUploads/allUploads
(grep '^Username;email;submission\ data;level;points$' './summaryUploads/allUploads' >> /dev/null) || (echo "Username;email;submission data;level;points" >> ./summaryUploads/allUploads)
cat ./uploadedFiles/datasetHacklab-*.txt >> ./summaryUploads/allUploads
rm ./uploadedFiles/datasetHacklab-*