#!/bin/bash
# start a tmux-session and all windows for level 01 

lxc exec $module-lvl01-$USER-c02 -- tshark -i eno1 &>> control.log &

# create the session and split panes
tmux new-session -s hacklab -n level01 -d 'lxc exec $module-lvl01-$USER-c02 -- tshark -i eno1; bash -i 2> /dev/null'\;\
    split-window -v -d 'lxc shell $module-lvl01-$USER-c01'\;\
    split-window -h -d 'lxc exec $module-lvl01-$USER-c03 -- tshark -i eno1; bash -i 2> /dev/null'\;\
    select-pane -D
    
tmux new-window -t hacklab:1 -n help 'print_paragraph_from_file synopsis ./story.txt; bash -i 2> /dev/null' # create a new window and run
tmux new-window -t hacklab:2 -n topology 'cat topology.txt; bash -i 2> /dev/null'                           # create a new window and run
tmux select-window -t hacklab:1                                                                             # select the window who will start at first
tmux -2 attach-session -t hacklab > /dev/null                                                               # to attach the session

lxc exec $module-lvl01-$USER-c02 -- killall tshark; sleep 1                                                 # wait long enough to kill tshark

tmux kill-session -t hacklab                                                                                # clean-up tmux session after use
