#!/bin/bash

# allow users to retry n times

# $1: max number of retries

for (( try=0; try<$1; try++ )); do
    echo "You've got $(( $1 - $try )) tries left."
    while : ; do
        unset choice
        echo -n "Do you want to play again? [Y|n]: "
        read -n 1 choice
        case $choice in
            Y|y) ./tmux_session; clear; ./evaluation; sleep .5; break ;;
            N|n) try=$1; break ;;
            *) echo " - wrong option: $choice" ;;
        esac
    done
done
