#!/bin/bash

# print '    >>>    '
# each '>' is being printed with a delay
# $1: delay time [default: 0.2s]

if [ $# -eq 1 ]; then time=$1; else time=0.2s; fi
echo -n "    "; sleep $time; echo -n ">"; sleep $time; echo -n ">"; sleep $time; echo -n ">"; sleep $time; echo -n "    "