#!/bin/bash

blink=`echo -en "\e[5m"`
green=`echo -en "\e[32m"`
purple=`echo -en "\e[35m"`
default=`echo -en "\e[39m"`

file=$(readlink -f $1)
file_name=$(basename $file)

if [ "$file_name" = "win.txt" ] || [ "$file_name" = "insufficient.txt" ]; then
    while IFS= read -r line; do                                             # print each line from $file
        echo "${blink}${green}$line${default}"                              # apply color + reset to default
    done <$file
elif [ "$file_name" = "lost.txt" ]; then
    while IFS= read -r line; do                                             # print each line from $file
        echo "${blink}${purple}$line${default}"                             # apply color + reset to default
    done <$file
else echo "[$0] Error: invalid parameter: $@"; exit 1; fi

setterm -blink off                                                          # reset blinking letters
