#!/bin/bash

# read text file from startline till endline, wait $3 seconds, then print next line
# e.g. this gets called from print_paragraph_from_file with appropriate parameters

# $1: first line
# $2: last line
# $3: path/to/some/file
# $4: pause time

for (( i=$1 ; i<=$2 ; i++ )); do
    line=$(awk 'NR=='$i'{ print}' $3)       # store line i from file $3 in $line
    typeit_like_handwriting "$line"         # typeit function types every char of $line slowly
    sleep $4
    echo -e "\n"
done
