#!/bin/bash

# simulate handwriting by varying inter-letter pauses
# $1: pause factor [default: 0.005]
# $2: random modul [default: 40]

if [[ $# -eq 3 ]]; then fac=$1; mod=$2; text="$3"; else fac=.005; mod=40; text="$1"; fi 
IFS=''
while read -n1 c; do
    echo -en "$c"
    sleep $fac$(( RANDOM % $mod ))
done <<< $text