#!/bin/bash

# $1 --> username
# $2 --> level number

function pushDatasetToServer() {
    if [ -f localDataset.txt.gpg ]; then                                        #checks if the file exists
        timeStamp=$(date +%s)
        echo "sending dataset..."
        scp ./localDataset.txt.gpg hacklab@10.215.33.91:/home/hacklab/uploadedFiles/datasetHacklab-${timeStamp}-${RANDOM}.txt.gpg       #copies the encrypted file to the database
    fi
}

echo -n "Do you want to upload your points? [Y|n]: "
read -n 1 userInput
case $userInput in
    Y|y)
        importGpgKey &&                                                                                             `#checks if the key already exists --> imports the correct public key`\
        . authentication &&                                                                                        
        echo "$email;$(date +%c);$1;Level $2;$points"                                                               `#text we want to add to database`\
        | gpg -e --always-trust -a -r 590659F58937BD0A763D1DCDD07DBD27DEB068CF > localDataset.txt.gpg &&            `#encrypts the text with the public key of the database`\
        pushDatasetToServer ;;     
    N|n) return 0 ;;
    *) echo -e "\nWrong option\n" ; upload;;
esac
