#!/bin/bash

# pause until user interaction (one key) - FIXME: stdin buffer overflow 
# immediate "Ok!" prompt to avoid user irritation due to pause times

echo -n "Press any key to continue... "
read -n1 -s
echo -e "Ok!\n"