-  hosts: 
    - localhost
   #remote_user: test
   connection: ssh
   gather_facts: true
   become: yes
   tasks:
     - name: Gather facts
       ansible.builtin.debug:
          var: ansible_facts
