#!/bin/bash

export module=networks
export level=2

cd $(dirname "$0")
PATH=$PATH:$(dirname "$0")

echo -e "\n\nCheck for existing containers..."; sleep .5
lxc info $module-lvl02-$USER-c01 &> /dev/null && ( echo -e "Error: wait for containers to be removed.\n" && (level_stop $module $level 3 &) && exit 1 )
lxc info $module-lvl02-$USER-c02 &> /dev/null && ( echo -e "Error: wait for containers to be removed.\n" && (level_stop $module $level 3 &) && exit 1 )
lxc info $module-lvl02-$USER-c03 &> /dev/null && ( echo -e "Error: wait for containers to be removed.\n" && (level_stop $module $level 3 &) && exit 1 )

(level_start $module $level 3 &)            # initiate level infrastructure

. print_story_or_skip                       # y: story time, n: skip

./tmux_session; clear                       # <- actual gameplay - create different windows, DON'T SOURCE IT
. ./evaluation                              # needs to be sourced (with '.') to retrieve points 
. allow_retry                               # allows user to play again without destructing containers
. upload_score_to_nibelung $module $level   # upload + authentication

# end tmux session                          # clean up
(level_stop $module $level 3 &)             # remove level infrastructure

exit 0
