#!/bin/bash

export module=networks
export level=2

cd $(dirname "$0")
PATH=$PATH:$(dirname "$0")
echo -e "\nyou chose level $level. starting..."
(level_start $module $level 3 &)            # initiate level infrastructure

. print_story_or_skip                       # y: story time, n: skip

echo -ne "\nyou chose level $level. starting..."
while : ; do
    echo -n "."; sleep .5
    state=$( lxc info $module-lvl01-c03-$USER 2> /dev/null | grep '(global)' | sed s/'.*('/'('/ ) &> /dev/null
    [ "$state" = '(global)' ] && break
done

tmux_session; clear                         # <- actual gameplay - create different windows
. ./evaluation                              # needs to be sourced (with '.') to retrieve points 
. allow_retry                               # allows user to play again without destructing containers
. upload_score_to_nibelung $module $level   # upload + authentication

#end tmux session                           # clean up
(level_stop $module $level 3 &)             # remove level infrastructure

exit 0
